"""Merge bulk_part*.py into hole_certificates_bulk.py."""
import importlib.util
import sympy as sp
import gen_bulk as GB

roots, boxes = [], []
for k in range(5):
    spec = importlib.util.spec_from_file_location(f"p{k}", f"bulk_part{k}.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    roots.append(mod.DATA["root"])
    boxes += mod.DATA["boxes"]
ncert = sum(1 for b in boxes if b["kind"] == "certified")
print(f"{len(boxes)} boxes ({ncert} certified)")
with open("hole_certificates_bulk.py", "w") as f:
    f.write("# generated by gen_bulk_strip.py x5 + merge_bulk.py\n")
    f.write("DATA = " + repr({"roots": roots, "boxes": boxes}) + "\n")
print("written hole_certificates_bulk.py")
