#!/usr/bin/env python3
"""Generate the proof-free statements-and-figures reading edition.

The canonical manuscript remains authoritative.  This script follows its active
``\\input`` closure, removes every ``proof`` environment, applies the explicit
``STATEMENTS-ONLY`` source markers, and writes a self-contained derived source
tree under ``arrange/paper_draft/statements_only``.
"""

from __future__ import annotations

import argparse
import re
import shutil
import sys
import tempfile
from collections import Counter
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "arrange" / "paper_draft"
OUTPUT = SOURCE / "statements_only"
ENTRYPOINT = SOURCE / "main.tex"

GENERATED_HEADER = (
    "% Generated by tools/generate_statements_only_paper.py.\n"
    "% Do not edit this derived file; edit the canonical paper source instead.\n\n"
)

FORMAL_ENVIRONMENTS = (
    "theorem",
    "lemma",
    "proposition",
    "corollary",
    "definition",
    "remark",
)
PRESERVED_ENVIRONMENTS = FORMAL_ENVIRONMENTS + ("figure",)

OMISSION_IDS = {
    "universal-beta-rationalization",
    "strategy2-low-root-derivation",
    "strategy4-verifier-calculations",
    "strategy4-provenance-comments",
}

REPLACEMENTS = {
    "paper-title": r"""\title[Statements and figures edition]
{Seven Open Unit Equilateral Triangles Do Not Cover a Regular Unit Hexagon:\\
A Statements-and-Figures Reading Edition}
""",
    "paper-abstract": r"""\begin{abstract}
This reading edition records the definitions, formal statements, explanatory
prose, and figures of the complete paper while omitting every proof body and
the calculation details used to establish the results.  Its main statement is
that a regular hexagon of side length one cannot be covered by seven open
equilateral triangles of side length one.  The canonical C-triangle/V-triangle
classification routes a hypothetical cover to four mechanisms: trace-length
deficit, propagation of boundary-reach lower bounds, area loss, and an
equilateral-enclosure obstruction for nine forced points.  The unabridged
paper and exact certificates remain the authority for all proofs.
\end{abstract}
""",
    "paper-maketitle": r"""\maketitle
\begin{center}
\fbox{\parbox{0.91\textwidth}{\small
\textbf{Scope of this edition.} All theorem, lemma, proposition, corollary,
definition, and remark statements are retained, together with the paper's
explanatory prose and figures. Proof environments and calculation-only
certificate material are omitted. The unabridged paper and exact certificates
remain the proof authority.}}
\end{center}
\medskip
""",
    "introduction-heading": (
        "\\section{Introduction and Result Outline}\n"
    ),
    "canonical-labeling": r"""For a hypothetical cover, use the canonical labeling
\[
 U_C,U_0,\ldots,U_5
\]
with
\[
 O\in U_C,
 \qquad
 V_i\in U_i.
\]
We call $U_C$ the \emph{C triangle} and $U_i$ the \emph{V triangle at
$V_i$}.  Set
\[
 T_C=\overline{U_C},\qquad T_i=\overline{U_i}.
\]
""",
    "common-trace-count": r"""Let $N_{\mathrm{sp}}$ be the number of V triangles of type
$\Vdone,\Vdtwo,$ or $\Tlike$.  The corresponding count of V triangles that
are either supercritical or meet an adjacent radial segment in positive
length is
\[
 N_++N_{\mathrm{sp}}.
\]
Every CE1/CE2 configuration with $N_++N_{\mathrm{sp}}\ge3$ is excluded by
the trace-length statement on $S$.
""",
    "reading-edition-organization": r"""\subsection{Organization of the reading edition}

Section~\ref{sec:structure-common} records the structural classification,
strict handoff selection, midpoint facts, and signed C-triangle normal form.
Sections~\ref{sec:trace-length}--\ref{sec:nine-point} record the statements
for the four mechanisms, and Section~\ref{sec:assembly} records the exhaustive
conclusion.  Proof bodies and calculation details are omitted throughout.
""",
    "routing-classification-reference": r"""The full classification is
Proposition~\ref{prop:exhaustive-structural-reduction}.
""",
    "structure-wrapper-introduction": r"""This section records the finite reduction used by every later method: the
open--closed scaling equivalence, the C-triangle and V-triangle
classifications, strict boundary handoffs, midpoint facts, exhaustive routing,
and the signed center normal form used by the trace and propagation arguments.
The proofs are omitted in this reading edition.
""",
    "trace-wrapper-introduction": r"""The first mechanism compares the total one-dimensional trace available from
the seven triangles with the length of either the perimeter $\partial H$ or
the full skeleton $S$.  This section records the local trace estimates, the
master perimeter deficit, the conditional skeleton theorem, and every routed
application; their proofs are omitted.
""",
    "propagation-wrapper-introduction": r"""The second mechanism converts a backward boundary reach and a radial reach
into an upper bound for the forward reach of the same V triangle. Coverage of
the next edge then produces a lower bound for the next backward reach.  This
section records the common equilateral-enclosure calculus, center-assisted
path budget, exceptional T3-like and Vd placements, and the branchwise
propagation statements.  Formalization-only registries remain repository
verification objects and are not printed here.
""",
    "area-wrapper-introduction": r"""The third mechanism measures the normalized area forced outside $H$ by a
V triangle with prescribed boundary reaches.  The local square-loss and
T3-like estimates are stated first, followed by the two CE0 area-branch
conclusions.
""",
    "nine-point-wrapper-introduction": r"""The fourth mechanism applies when all six V triangles are Vd0, the boundary
is covered, and exactly one V triangle is supercritical.  Six radial points
and three asymmetric frontier points are forced into the C triangle.  This
section records the construction, support-arc, and final enclosure statements.
""",
    "trace-subadditivity": r"""For a closed triangle $T$ and a rectifiable target $E$, define
\[
 L_E(T)=\mathcal H^1(T\cap E).
\]
For the closures of a hypothetical open cover, the trace bound is
\begin{equation}
 \mathcal H^1(E)
 \le L_E(T_C)+\sum_{i=0}^5L_E(T_i).
 \label{eq:length-subadditivity}
\end{equation}
All estimates in this section concern full traces and therefore apply to
assigned measurable subsets of those traces.
""",
    "supercritical-cell-statement": r"""For the remaining cap, use the following selected supercritical cell.  In
local directions $u,v$ meeting at $120^\circ$, if a closed unit triangle
contains $0,au,bv,c(u+v)$ with $0\le a\le b\le1$ and $a+b>1$, then
\begin{equation}
 \begin{aligned}
 &a^2+ab+b^2\le1,\qquad c\le\frac12,\\
 &(a^2-1)c^2+(2ab^2+b)c+(b^4-b^2)\le0,
 \end{aligned}
 \label{eq:supercritical-admissible-cell}
\end{equation}
where $c$ lies on the connected component containing $c=0$.
""",
    "signed-propagation-statement": r"""Let a nonsupercritical V triangle have maximal reaches
$(A_i,B_i,C_i)$ with $A_i\ge z$ and $C_i\ge c_i>1/2$.
If the next boundary handoff gives $A_{i+1}\ge1-B_i$, then
\begin{equation}
 A_{i+1}\ge\Phi_{c_i}(z).
 \label{eq:reader-actual-propagation}
\end{equation}
Every composition below abbreviates repeated use of this statement.
""",
    "signed-three-map-target": r"""The corresponding scalar target is
""",
    "signed-center-scalar-remark": r"""The geometric one-gap interface is common, but
\eqref{eq:signed-two-threshold} is not valid on the full CE1 sign domain.
Thus the merger stops at
Proposition~\ref{prop:signed-one-gap-interface}; the CE1 selected-$Q_+$
clause and the CE2 threshold clause require different scalar arguments for
the same target \eqref{eq:signed-three-map-target}.
""",
    "universal-support-reference": r"""The corresponding exact admissible-set statement is recorded in
Section~\ref{sec:admissible-set-derivation}.
""",
    "universal-radical-summary": r"""For $0\le x\le1$, define
\begin{equation}
 \omega(x)=\sqrt{1-x+x^2},
 \qquad
 \sigma(x)=1-\omega(x).
 \label{eq:universal-radical}
\end{equation}
In the signed C-triangle calculus,
\[
 E=\omega(R),\qquad \eta=\sigma(R).
\]
""",
    "universal-affine-coefficient": r"""For every coefficient $\lambda$ valid on the relevant selected arc,
""",
    "strategy2-roadmap-introduction": r"""The following statements collect eight geometric outputs: the one- and
two-gap endpoint inequalities, the CE1 and CE2 return inequalities, the
support-isolated T3 endpoint inequality, the common adjacent-exception
obstruction, and the two Vd separation statements.  Their labels are
\ref{thm:s2-geom-e1}, \ref{thm:s2-geom-e2},
\ref{thm:s2-geom-r1}, \ref{thm:s2-geom-r2},
\ref{thm:s2-geom-t3}, \ref{thm:s2-geom-sc},
\ref{thm:s2-geom-vd-adjacent}, and
\ref{thm:s2-geom-vd-nonadjacent}.  The detailed proofs are omitted.
""",
    "strategy2-module-assembly": (
        "% Statements-and-figures Strategy 2 module assembly.\n"
    ),
    "strategy2-calculus-introduction": r"""Actual maximal reaches continue to be denoted by $(A_i,B_i,C_i)$, while
lowercase letters denote prescribed reach lower bounds.  The complete paper
establishes all estimates analytically; this edition retains their statements.
""",
    "strategy2-t3-package-introduction": r"""Figure~\ref{fig:ce1-ce2-n0-all-vd0} gives a common schematic for the package
recorded below.
""",
    "strategy2-package-figure-caption": r"""\caption{Schematic view of the common CE1/CE2, $N_+=0$, all-Vd0 boundary
package, not to scale.  The C triangle and three representative Vd0 vertex
triangles are shown; the remaining three triangles are omitted for
readability.  The simultaneous placement is not a candidate cover, and no
conclusion depends on visual inspection.}
""",
    "boundary-propagation-result-wording": r"""Boundary-reach propagation gives the following exclusions:
""",
    "vd-profile-introduction": r"""This subsection records the local profile estimates used by the
one-special-triangle branches; their proofs are omitted.
""",
    "vd-replacement-introduction": r"""The complete four-branch T3 endpoint statement is
Lemma~\ref{lem:407-four-label-loss}; its authenticated source crosswalk is
kept in the paper source ledger rather than printed a second time.  The next
statement is the two-chart replacement needed for the Vd branch.
""",
    "ce2-placement-introduction": r"""The following proposition is the CE2 exactly-one-Vd placement assembly used
by the complete paper.  It cites the placement lemmas and the two-chart
replacement recorded above.
""",
    "area-details-introduction": r"""This section records the local inequalities and cyclic estimates used in the
area-loss argument.
""",
    "area-figure-caption": r"""\caption{Schematic views of Method~3, not to scale.  The local panel
shows one V triangle with boundary reaches $a,b$, and the global panel
shows the six cyclic triangles.  Only the darker portions represent area
retained inside $H$; the stated inequalities, rather than the picture, give
the comparison.}
""",
    "nine-point-details-introduction": r"""This section records the exact frontier, witness, sign, and cap-overlap
statements for the direct nine-point obstruction.  The result is independent
of the C-triangle class: all six V triangles are $\Vdzero$, they cover the
full boundary, and exactly one actual boundary V triangle is supercritical.
Six common radial points and three asymmetric points are forced into the
C triangle.
""",
    "caliper-introduction": r"""We record the finite caliper criterion used below; its verification is omitted
from this reading edition.
""",
    "strategy4-certificate-introduction": r"""The two mixed cap overlaps in Method~4 are certified in the complete paper
and its authenticated exact certificate package.  This appendix retains the
definitions and formal statements; calculation details and provenance data
are omitted.  The complete certificate package remains available in the
repository.
""",
    "strategy4-kappa-definition": r"""Put
\[
 \kappa=4s^3-2s+m>0.
\]
""",
    "strategy4-certificate-target": r"""Lemma~\ref{lem:paper-branchwise-cbar} gives
$0<\bar\eta\le\eta=h(1-c_*)$.  The certificate targets the mixed
intersections for the smaller disks with radii
$2\bar\eta,\bar\eta,2\bar\eta$.
""",
    "strategy4-core-reduction-statement": r"""\subsection{Exact residual statement}

For $B\in\{L,T\}$ and $X\in\{A,C\}$, the exact certificate uses eight core
polynomials in $\mathbb Z[U,z]$, specified by
\begin{equation}
 \operatorname{num}(Q_{B,X})
 =32(K+3)^2
 \{A_{B,X}(U,z)+D B_{B,X}(U,z)\}.
 \label{eq:certificate-core-reduction}
\end{equation}
""",
    "strategy4-certificate-availability": r"""The authenticated exact data and verifiers remain available in the repository
package supporting the complete paper.
""",
    "strategy4-certificate-remark-heading": "\\begin{remark}[Certificate availability]\n",
    "exhaustive-assembly": r"""\section{Exhaustive Assembly Statement}
\label{sec:assembly}

Table~\ref{tab:routing} gives the exhaustive case organization for the main
theorem.  In the complete paper, every row is excluded by the trace-length,
boundary-propagation, area-loss, or nine-point results recorded above.  The
resulting conclusions are Theorem~\ref{thm:main} and
Corollary~\ref{cor:expanded-closed}.
""",
}

EXPECTED_REPLACEMENT_IDS = set(REPLACEMENTS)
MARKER_RE = re.compile(
    r"^\s*% STATEMENTS-ONLY-(OMIT|REPLACE)-(BEGIN|END): "
    r"([a-z0-9][a-z0-9-]*)\s*$"
)
PROOF_BEGIN_RE = re.compile(r"\\begin\{proof\}(?:\[[^]]*\])?")
PROOF_END_RE = re.compile(r"\\end\{proof\}")
FORMAL_BLOCK_RE = re.compile(
    r"\\begin\{(?P<env>" + "|".join(PRESERVED_ENVIRONMENTS) + r")\}"
    r"(?:\[[^]]*\])?.*?\\end\{(?P=env)\}",
    re.DOTALL,
)

IGNORED_OUTPUT_FILES = {
    "main.pdf",
    "main.aux",
    "main.fdb_latexmk",
    "main.fls",
    "main.log",
    "main.out",
    "main.toc",
    "main.xdv",
    "main.synctex.gz",
    "main.rebuilt1.pdf",
    "main.rebuilt2.pdf",
    "main.rebuilt1.log",
    "main.rebuilt2.log",
}


class GenerationError(RuntimeError):
    """A fail-closed source or synchronization error."""


def strip_tex_comments(text: str) -> str:
    """Remove TeX comments while retaining escaped percent signs."""

    return re.sub(r"(?m)(?<!\\)%.*$", "", text)


def active_tex(text: str) -> str:
    r"""Return TeX-visible material, excluding comments and ``\iffalse`` blocks."""

    text = strip_tex_comments(text)
    inactive = re.compile(r"\\iffalse\b(?:(?!\\iffalse\b|\\fi\b).)*\\fi\b", re.S)
    previous = None
    while text != previous:
        previous = text
        text = inactive.sub("", text)
    if re.search(r"\\(?:iffalse|fi)\b", text):
        raise GenerationError("unsupported or unbalanced TeX conditional in active source")
    return text


def within_source(path: Path) -> Path:
    resolved = path.resolve()
    try:
        resolved.relative_to(SOURCE.resolve())
    except ValueError as exc:
        raise GenerationError(f"paper input escapes source tree: {path}") from exc
    return resolved


def collect_active_tex(path: Path, seen: set[Path]) -> None:
    """Collect the active recursive TeX input closure."""

    path = within_source(path)
    if path in seen:
        return
    if not path.is_file() or path.is_symlink():
        raise GenerationError(f"missing or symlinked TeX input: {path}")
    seen.add(path)
    text = active_tex(path.read_text(encoding="utf-8"))
    for name in re.findall(r"\\input\{([^}]+)\}", text):
        child = path.parent / name
        if child.suffix == "":
            child = child.with_suffix(".tex")
        collect_active_tex(child, seen)


def collect_graphics(tex_paths: set[Path]) -> set[Path]:
    """Resolve the static graphics referenced by the active TeX closure."""

    graphics: set[Path] = set()
    pattern = re.compile(r"\\includegraphics(?:\[[^]]*\])?\s*\{([^}]+)\}", re.S)
    for tex_path in tex_paths:
        text = active_tex(tex_path.read_text(encoding="utf-8"))
        for name in pattern.findall(text):
            candidate = tex_path.parent / name.strip()
            candidates = [candidate]
            if candidate.suffix == "":
                candidates = [candidate.with_suffix(ext) for ext in (".pdf", ".png", ".jpg", ".jpeg")]
            matches = [within_source(item) for item in candidates if item.is_file()]
            if len(matches) != 1:
                raise GenerationError(
                    f"expected exactly one static graphic for {name!r} in {tex_path}"
                )
            if matches[0].is_symlink():
                raise GenerationError(f"refusing symlinked graphic: {matches[0]}")
            graphics.add(matches[0])
    return graphics


def apply_markers(text: str, source_name: str, seen_ids: dict[str, str]) -> str:
    """Apply explicit omission and replacement markers in one source file."""

    output: list[str] = []
    active: tuple[str, str] | None = None
    body: list[str] = []

    for line_number, line in enumerate(text.splitlines(keepends=True), start=1):
        match = MARKER_RE.match(line.rstrip("\r\n"))
        if match:
            kind, boundary, marker_id = match.groups()
            if boundary == "BEGIN":
                if active is not None:
                    raise GenerationError(
                        f"nested statements-only marker in {source_name}:{line_number}"
                    )
                if marker_id in seen_ids:
                    raise GenerationError(
                        f"duplicate statements-only marker {marker_id!r} in "
                        f"{seen_ids[marker_id]} and {source_name}:{line_number}"
                    )
                if kind == "OMIT" and marker_id not in OMISSION_IDS:
                    raise GenerationError(f"unknown omission marker {marker_id!r}")
                if kind == "REPLACE" and marker_id not in REPLACEMENTS:
                    raise GenerationError(f"unknown replacement marker {marker_id!r}")
                active = (kind, marker_id)
                body = []
                seen_ids[marker_id] = f"{source_name}:{line_number}"
                continue

            if active != (kind, marker_id):
                raise GenerationError(
                    f"unmatched statements-only marker in {source_name}:{line_number}"
                )
            original = "".join(body)
            if FORMAL_BLOCK_RE.search(original):
                raise GenerationError(
                    f"marker {marker_id!r} encloses a preserved statement or figure"
                )
            if kind == "REPLACE":
                replacement = REPLACEMENTS[marker_id]
                output.append(replacement)
                if replacement and not replacement.endswith("\n"):
                    output.append("\n")
            else:
                output.append(
                    f"% Calculation-only material omitted ({marker_id}).\n"
                )
            active = None
            body = []
            continue

        if active is None:
            output.append(line)
        else:
            body.append(line)

    if active is not None:
        raise GenerationError(f"unterminated statements-only marker in {source_name}")
    return "".join(output)


def strip_proofs(text: str, source_name: str) -> tuple[str, int]:
    """Remove complete proof environments, rejecting ambiguous source forms."""

    output: list[str] = []
    in_proof = False
    removed = 0
    for line_number, line in enumerate(text.splitlines(keepends=True), start=1):
        visible_line = strip_tex_comments(line).strip()
        begins = PROOF_BEGIN_RE.findall(visible_line)
        ends = PROOF_END_RE.findall(visible_line)
        if begins or ends:
            if begins and ends:
                raise GenerationError(
                    f"proof begin/end share a line in {source_name}:{line_number}"
                )
            if begins:
                if in_proof or len(begins) != 1 or not PROOF_BEGIN_RE.fullmatch(visible_line):
                    raise GenerationError(
                        f"ambiguous proof begin in {source_name}:{line_number}"
                    )
                in_proof = True
                removed += 1
                output.append(
                    f"% Proof environment omitted (source: {source_name}).\n"
                )
                continue
            if not in_proof or len(ends) != 1 or not PROOF_END_RE.fullmatch(visible_line):
                raise GenerationError(
                    f"ambiguous proof end in {source_name}:{line_number}"
                )
            in_proof = False
            continue
        if not in_proof:
            output.append(line)
    if in_proof:
        raise GenerationError(f"unterminated proof environment in {source_name}")
    return "".join(output), removed


def preserved_blocks(texts: dict[Path, str]) -> Counter[tuple[str, str]]:
    """Return exact formal-statement, remark, and figure blocks."""

    blocks: Counter[tuple[str, str]] = Counter()
    for text in texts.values():
        for match in FORMAL_BLOCK_RE.finditer(active_tex(text)):
            blocks[(match.group("env"), match.group(0))] += 1
    return blocks


def environment_counts(blocks: Counter[tuple[str, str]]) -> dict[str, int]:
    return {
        environment: sum(
            count for (block_environment, _), count in blocks.items()
            if block_environment == environment
        )
        for environment in PRESERVED_ENVIRONMENTS
    }


def validate_references(texts: dict[Path, str]) -> None:
    """Reject duplicate labels and references whose targets were stripped."""

    labels: dict[str, Path] = {}
    references: list[tuple[str, Path]] = []
    for path, raw in texts.items():
        text = active_tex(raw)
        for label in re.findall(r"\\label\{([^}]+)\}", text):
            if label in labels:
                raise GenerationError(
                    f"duplicate generated label {label!r}: {labels[label]} and {path}"
                )
            labels[label] = path
        for reference in re.findall(
            r"\\(?:eqref|ref|pageref|cref|Cref|autoref)\{([^}]+)\}", text
        ):
            references.append((reference, path))
    unresolved = [
        f"{reference} ({path})"
        for reference, path in references
        if reference not in labels
    ]
    if unresolved:
        raise GenerationError(
            "generated source has unresolved references:\n" + "\n".join(unresolved)
        )


def build_expected_tree() -> tuple[dict[Path, bytes], dict[str, int], int]:
    """Construct and validate the complete expected derived source tree."""

    tex_paths: set[Path] = set()
    collect_active_tex(ENTRYPOINT, tex_paths)
    graphics = collect_graphics(tex_paths)
    canonical_texts = {
        path.relative_to(SOURCE): path.read_text(encoding="utf-8")
        for path in tex_paths
    }
    canonical_blocks = preserved_blocks(canonical_texts)
    canonical_proofs = sum(
        len(PROOF_BEGIN_RE.findall(active_tex(text)))
        for text in canonical_texts.values()
    )
    if canonical_proofs == 0:
        raise GenerationError("canonical manuscript unexpectedly has no proofs")

    seen_ids: dict[str, str] = {}
    marked_texts: dict[Path, str] = {}
    generated_texts: dict[Path, str] = {}
    removed_proofs = 0
    for relative, text in sorted(canonical_texts.items()):
        transformed = apply_markers(text, relative.as_posix(), seen_ids)
        marked_texts[relative] = GENERATED_HEADER + transformed
        transformed, removed = strip_proofs(transformed, relative.as_posix())
        removed_proofs += removed
        generated_texts[relative] = GENERATED_HEADER + transformed

    expected_ids = OMISSION_IDS | EXPECTED_REPLACEMENT_IDS
    actual_ids = set(seen_ids)
    if actual_ids != expected_ids:
        missing = sorted(expected_ids - actual_ids)
        extra = sorted(actual_ids - expected_ids)
        raise GenerationError(
            f"statements-only marker inventory mismatch; missing={missing}, extra={extra}"
        )

    expected_blocks = preserved_blocks(marked_texts)
    generated_blocks = preserved_blocks(generated_texts)
    if generated_blocks != expected_blocks:
        lost = expected_blocks - generated_blocks
        added = generated_blocks - expected_blocks
        raise GenerationError(
            "formal statement/remark/figure preservation after declared "
            "transformations failed: "
            f"lost={sum(lost.values())}, added={sum(added.values())}"
        )

    generated_proofs = sum(
        len(PROOF_BEGIN_RE.findall(active_tex(text)))
        for text in generated_texts.values()
    )
    if generated_proofs:
        raise GenerationError(f"generated source retains {generated_proofs} proofs")
    if removed_proofs > canonical_proofs:
        raise GenerationError("removed more proofs than the canonical source contains")

    validate_references(generated_texts)

    expected: dict[Path, bytes] = {
        relative: text.encode("utf-8")
        for relative, text in generated_texts.items()
    }
    for graphic in graphics:
        expected[graphic.relative_to(SOURCE)] = graphic.read_bytes()
    expected[Path("README.md")] = (
        "# Statements-and-figures reading edition\n\n"
        "This directory is generated from the canonical paper in the parent directory.\n"
        "It retains the explanatory prose, definitions, formal statements, remarks, and\n"
        "figures while omitting proof environments and explicitly marked calculation-only\n"
        "material. Do not edit generated files directly.\n\n"
        "Regenerate from the repository root:\n\n"
        "```bash\n"
        "python tools/generate_statements_only_paper.py\n"
        "```\n\n"
        "Build from this directory:\n\n"
        "```bash\n"
        "latexmk -xelatex -interaction=nonstopmode -halt-on-error main.tex\n"
        "```\n\n"
        "The complete manuscript and authenticated certificates remain the proof authority.\n"
    ).encode("utf-8")
    return expected, environment_counts(canonical_blocks), canonical_proofs


def output_files() -> dict[Path, bytes]:
    """Read managed output files, excluding PDFs and TeX build intermediates."""

    if not OUTPUT.exists():
        return {}
    if not OUTPUT.is_dir() or OUTPUT.is_symlink():
        raise GenerationError(f"invalid generated output directory: {OUTPUT}")
    files: dict[Path, bytes] = {}
    for path in OUTPUT.rglob("*"):
        if path.is_symlink():
            raise GenerationError(f"refusing symlink in generated output: {path}")
        if not path.is_file():
            continue
        relative = path.relative_to(OUTPUT)
        if len(relative.parts) == 1 and relative.name in IGNORED_OUTPUT_FILES:
            continue
        files[relative] = path.read_bytes()
    return files


def check_output(expected: dict[Path, bytes]) -> None:
    actual = output_files()
    missing = sorted(expected.keys() - actual.keys())
    stale = sorted(actual.keys() - expected.keys())
    changed = sorted(
        path for path in expected.keys() & actual.keys()
        if expected[path] != actual[path]
    )
    if missing or stale or changed:
        details = []
        if missing:
            details.append("missing: " + ", ".join(map(str, missing)))
        if stale:
            details.append("stale: " + ", ".join(map(str, stale)))
        if changed:
            details.append("changed: " + ", ".join(map(str, changed)))
        raise GenerationError("statements-only source is not current; " + "; ".join(details))


def synchronize_output(expected: dict[Path, bytes]) -> None:
    """Synchronize generated files while preserving any compiled PDF and auxiliaries."""

    OUTPUT.mkdir(parents=True, exist_ok=True)
    if OUTPUT.is_symlink():
        raise GenerationError(f"refusing symlinked output directory: {OUTPUT}")

    actual = output_files()
    for relative in sorted(actual.keys() - expected.keys(), reverse=True):
        target = OUTPUT / relative
        if target.is_symlink() or not target.is_file():
            raise GenerationError(f"refusing unsafe stale output path: {target}")
        target.unlink()

    for relative, payload in sorted(expected.items()):
        target = OUTPUT / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        if target.exists() and (target.is_symlink() or not target.is_file()):
            raise GenerationError(f"refusing unsafe generated output path: {target}")
        with tempfile.NamedTemporaryFile(dir=target.parent, delete=False) as temporary:
            temporary.write(payload)
            temporary_path = Path(temporary.name)
        temporary_path.replace(target)

    for directory in sorted(
        (path for path in OUTPUT.rglob("*") if path.is_dir()),
        key=lambda path: len(path.parts),
        reverse=True,
    ):
        if not any(directory.iterdir()):
            directory.rmdir()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify that the tracked derived source is current without writing files",
    )
    args = parser.parse_args()

    try:
        expected, counts, proof_count = build_expected_tree()
        if args.check:
            check_output(expected)
            action = "verified"
        else:
            synchronize_output(expected)
            check_output(expected)
            action = "generated"
    except GenerationError as exc:
        print(f"generate_statements_only_paper: {exc}", file=sys.stderr)
        return 1

    formal_count = sum(counts[environment] for environment in FORMAL_ENVIRONMENTS)
    print(
        f"{action} {OUTPUT.relative_to(ROOT)}: "
        f"{formal_count} formal statements/remarks, "
        f"{counts['figure']} figures, {proof_count} proof environments omitted"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
