#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PROOF = ROOT / "proof"
MANIFEST = PROOF / "MANIFEST.txt"
EXCLUDED = {"MANIFEST.txt"}


def render() -> str:
    files = []
    for path in PROOF.rglob("*"):
        if not path.is_file():
            continue
        relative = path.relative_to(PROOF).as_posix()
        if relative in EXCLUDED or "__pycache__" in path.parts or path.suffix == ".pyc":
            continue
        files.append(relative)
    return (
        "# Proof Manifest\n\n"
        "Paths are relative to this `proof/` directory. This file is generated by\n"
        "`tools/generate_proof_manifest.py`; CI checks the listing in both directions.\n\n"
        + "\n".join(sorted(files))
        + "\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not MANIFEST.is_file() or MANIFEST.read_text(encoding="utf-8") != expected:
            raise SystemExit("proof/MANIFEST.txt is stale")
    else:
        MANIFEST.write_text(expected, encoding="utf-8")


if __name__ == "__main__":
    main()
